#ifndef __CocosTween23__Ease23__
#define __CocosTween23__Ease23__

namespace cocosTween23
{
enum class Ease23
{
    Linear,
    SineIn,
    _1_SineIn,
    SineOut,
    _1_SineOut,
    SineInOut,
    _1_SineInOut,
    QuadIn,
    _2_QuadIn,
    QuadOut,
    _2_QuadOut,
    QuadInOut,
    _2_QuadInOut,
    CubicIn,
    _3_CubicIn,
    CubicOut,
    _3_CubicOut,
    CubicInOut,
    _3_CubicInOut,
    QuartIn,
    _4_QuartIn,
    QuartOut,
    _4_QuartOut,
    QuartInOut,
    _4_QuartInOut,
    QuintIn,
    _5_QuintIn,
    QuintOut,
    _5_QuintOut,
    QuintInOut,
    _5_QuintInOut,
    ExpoIn,
    _6_ExpoIn,
    ExpoOut,
    _6_ExpoOut,
    ExpoInOut,
    _6_ExpoInOut,
    CircIn,
    _7_CircIn,
    CircOut,
    _7_CircOut,
    CircInOut,
    _7_CircInOut,
    ElasticIn,
    ElasticOut,
    ElasticInOut,
    BackIn,
    BackOut,
    BackInOut,
    BounceIn,
    BounceOut,
    BounceInOut,
};
} // namespace

#endif /* defined(__CocosTween23__Ease23__) */
